server.port=${PORT:8080}

# ─── User Identity ───────────────────────────────────────────────

app.user.name=minakshi_sharma
app.user.dob=16112003
app.user.email=minakshi0573.be23@chitkara.edu.in
app.user.roll=2310990573

# ─── Spring ─────────────────────────────────────────────────────

spring.application.name=bfhl
